server:
  port: 8888

limit:
  minaaa: 1
  maxaaa: 3
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    druid:

      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?serverTimezone=GMT
      username: shopping
      password: 1234
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
mybatis:
  mapper-locations: classpath*/com/neuedu/dao/*Dao.xml
  config-location: classpath:MybatisConfig.xml
