server:
  port: 8888

limit:
  minaaa: 1
  maxaaa: 3
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    druid:

      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?serverTimezone=GMT
      username: root
      password: root
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true

  thymeleaf:
    mode: HTML5

mybatis:
  mapper-locations:  classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:MybatisConfig.xml
#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
#输出sql到控制台
logging:
  level:
    com.neuedu.dao: debug
